### ISSUE TITLE
Testing ETS or serialisation in GenServer ?

### ISSUE THREAD

**Issue by DianaOlympos** [savonarola/redis_ets_benchmark#1]
Hello :simple_smile:

Someone pointed me that repo to show that Redis was faster and more efficient than ETS.

If i understand the code correctly, all the reading are serialised through a single GenServer, through the network.

It is interesting, but it is not the way ETS is meant to be used. Or it needs to be local table (original intend) or you would probably spawns process that would read concurently from ETS and send it back to the original caller through the network.

Would it be possible to point out on top of the README that this is a benchmark that compare Apple to Oranges and should not be used at all to decide to use Redis over ETS ?

And that it does not correspond at all to how this type of problems would be solved inside the Elixir and Erlang environment ?

Thanks for the hard work anyway, If you want to revisit that benchmark, I would happily help to build a more comprehensive benchmark, because i think there are definitely things to understand better about how a pure erlang/elixir storage through the network would scale :simple_smile:

**Comment by savonarola** [comment]
Hello! 

I do not see the case here, since the very first line of the README directly states that it is not a comparison of Redis and ets, not a comparison of Redis and some hypothetic super-fast ets-based distributed db,  it's a comparison of Redis and GenServer + ets + distributed Erlang.

Any other usages of ets are really beyond the scope of this benchmark.
Actually, a simple benchmark of local (and purposely nonoptimized for concurrent writes) ets was added in 023912096640198a2dbdc53dfa7715c11ed3b3a4, but that is not the case of interest.

Sorry for being misleaded by the benchmark, but it measures only what it states to measure :)

**Comment by benwilson512** [comment]
The issue is that this is not how one would actually use a "hypothetic super-fast ets-based distributed db". Nobody would ever serialize it through a single remote gen server because it obviates any and all benefits of the underlying data store.

**Comment by savonarola** [comment]
@benwilson512 I _really understand_ that, for example changing ets to map, dict, ... in the tested case will make absolutely no difference for the whole benchmark. The modelled server is optimised for nothing in _many_ aspects.

The purpose of benchmark was to make _simplest possible_ atomic storage _without any tuning_ and get _lower_ bounds of its productivity. 

By no means this benchmark can by used as an upper bound for remote ets storage.

**Comment by benwilson512** [comment]
If you want the simplest possible why even bother with the :ets? Can you at least say you were benchmarking redis vs a single genserver? I guess my point is that it's called the `RedisEtsBenchmark` but it's really just the `RedisGenServerBenchmark`.

People see this stuff and think it actually indicates that redis is faster than :ets.

**Comment by savonarola** [comment]
I think it's beacause _simplest possible atomic storage_ implies that we should actually store something in some way :)

**Comment by benwilson512** [comment]
GenServers have a state. It's in memory sure, but so is :ets. Each is precisely as persistent as the other.

**Comment by savonarola** [comment]
@benwilson512 Okay, you make me think that the name of the repo may be misleading.

I'll try to make things more clear so that this benchmark couldn't be used "against" ets :)
